config/routes.rb
ShoppingCart::Application.routes.draw do
  
  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :sessions, :only => [:new, :create, :destroy]

  resources :microposts

  resources :users

  resources :products

  resources :categories
  
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/contact', :to => 'pages#contact'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/signup', :to => 'users#new'
  match '/show_cart', :to => 'pages#show_cart'
  match '/pages/add_to_cart/:id', :to => 'pages#add_to_cart'
  match '/empty_cart', :to => 'pages#empty_cart'
  match '/remove_from_cart/:id', :to => 'pages#remove_from_cart'
  match '/save_order', :to => 'pages#save_order'
  match '/checkout', :to => 'pages#checkout'
  root :to => 'categories#home'

  match 'products/:id.pdf', :to => 'products#show', :defaults => {:format => 'pdf'}
  match '/products.pdf', :to => 'products#index', :defaults => {:format => 'pdf'}

  
 
end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<%= image_tag("logo.png", :alt => "Sample App", :class => "round") %>
	<nav class="round">
	  <ul>
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "My Cart", show_cart_path %></li>
		<% if signed_in? %>
			<li><%= link_to "Users", "/users" %></li>
			<% if session[:admin] == true && session[:user_id] %>
			<li><%= link_to "Category", "/categories" %></li>
			<li><%= link_to "Product", "/products" %></li>
			<% end %>
			<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
		<% else %>
			<li><%= link_to "Sign in", signin_path %></li>
		<% end %>
	  </ul>
	</nav>
	<div class="menu round">
		<ul class="cat">
			<li class="menu_link"><%= link_to "All", root_path %></li>
			<% getAllCategory %>
			<% @categories.each do |category| %>
			|<li class="menu_link"><%= link_to category.name, category %>
			<% end %>
		</ul>
	</div>
</header>


app/views/layouts/_product.html.erb
<div class="product">
	<span><%= link_to product.name, product %> </span><br />
	<span><%= image_tag(product.imagepath, :size => "100x100", :alt => product.name) %> </span><br />
	<span id="price"><b>$<%= product.price %> </b></span>&nbsp;&nbsp;&nbsp;&nbsp;
	<span style="vertical-align:middle;"><%= image_tag("btn_buynow_LG.gif") %> </span>
</div>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag    "application" %>
<%= stylesheet_link_tag    "home" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-CACHE">
<META HTTP-EQUIV="EXPIRES" CONTENT="0">
<META HTTP-EQUIV="PRAGMA" CONTENT="NO-CACHE">
<html>
	<head>
	  <title><%= title %></title>
	  <%= render 'layouts/stylesheets' %>
	  <%= csrf_meta_tags %>
	  <%= javascript_include_tag :application %>
	  <%= javascript_include_tag :validate %>
	</head>
	<body >
		<div class="container">
		  <%= render 'layouts/header' %>
		  <section class="round">
		    <% flash.each do |key, value| %>
				<div class="flash <%= key %>"><%= value %></div>
			<% end %>
			<%= yield %>
		  </section>
		  <%= render 'layouts/footer' %>
		</div>
	</body>
</html>